FROM ubuntu:20.04

RUN apt-get update && apt-get install -y tzdata iputils-ping iproute2 procps && \
    ln -fs /usr/share/zoneinfo/Europe/Madrid /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git nodejs npm && \
    git clone "https://github.com/gisai/SSR-master-server" && \
    cd SSR-master-server && \
    npm install && \
    npm install http-errors express

EXPOSE 3000

CMD ["node", "SSR-master-server/app.js"]
